name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch: 
  
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with latest articles
        uses: Prachi-Jamdade/update-content@v1.0.0
        with:
          feed_urls: https://medium.com/feed/@krrishmahar5
          article_limit: 5
          github_token: ${{ secrets.TOKEN_GITHUB }}

      
